import type { Sprite } from './sprites'

const palette = {
  K: '#15171d',
  F: '#e5b991',
  W: '#eee7d7',
  H: '#766052',
  T: '#ad8ddd',
  D: '#5f5678',
  Y: '#edc450',
  G: '#6fbd78',
}

export const VILLAGE_SPRITES: Record<string, Sprite> = {
  resident_librarian: {
    palette,
    rows: [
      '....HHHH....',
      '..HHHHHHHH..',
      '..HFFFFFFH..',
      '..FKKFFKKF..',
      '..FKWKKWKF..',
      '...FFFFFF...',
      '....KKKK....',
      '...TTTTTT...',
      '..TTTTTTTT..',
      '..FTTWWWTF..',
      '..FFTWDWFF..',
      '...TTWWWT...',
      '...DD..DD...',
      '...KK..KK...',
    ],
  },
  resident_smith: {
    palette: { ...palette, H: '#c1c4c7', T: '#d08c67', D: '#714938' },
    rows: [
      '...HHHHHH...',
      '..HHHHHHHH..',
      '..HFFFFFFH..',
      '..FKFFFFKF..',
      '...FHHHHF...',
      '...HHHHHH...',
      '....HHHH....',
      '..TTDDDDTT..',
      '.TTTDDDDTTT.',
      '.FTTDDDDTTF.',
      '.FFDDDDDDFF.',
      '...DDDDDD...',
      '...KK..KK...',
      '..KKK..KKK..',
    ],
  },
  resident_herbalist: {
    palette: { ...palette, H: '#795536', T: '#77ca88', D: '#47785f' },
    rows: [
      '.....GG.....',
      '..HHGGHHHH..',
      '.HHHHHHHHHH.',
      '.HHFFFFFFHH.',
      '.HFKFFFFKFH.',
      '.HHFFFFFFHH.',
      '..H.FFFF.H..',
      '...TTTTTT...',
      '..TTTTTTTT..',
      '..FTTYYTTF..',
      '..FFTTTTFF..',
      '...TTTTTT...',
      '...DD..DD...',
      '...KK..KK...',
    ],
  },
  resident_innkeeper: {
    palette: { ...palette, H: '#ad7458', T: '#e0b54f', D: '#806638' },
    rows: [
      '....WWWW....',
      '..WWWWWWWW..',
      '..HHHHHHHH..',
      '..HFFFFFFH..',
      '..FKFFFFKF..',
      '...FFFFFF...',
      '....FFFF....',
      '..TTWWWWTT..',
      '.TTTWWWWTTT.',
      '.FTTWWWWTTF.',
      '.FFWWWWWWFF.',
      '..TTTTTTTT..',
      '...DD..DD...',
      '..KKK..KKK..',
    ],
  },
  resident_bard: {
    palette: { ...palette, H: '#81538c', T: '#dc85b4', D: '#7c4777' },
    rows: [
      '.......W....',
      '....TTWT....',
      '...TTTTTT...',
      '..TTTTTTTT..',
      '..HFFFFFFH..',
      '..FKFFFFKF..',
      '...FFFFFF...',
      '....TTTT....',
      '..TTTTTTTT..',
      '..FTTYTTTF..',
      '..FFTYYTFF..',
      '...TTYYTT...',
      '...DD..DD...',
      '...KK..KK...',
    ],
  },
  resident_courier: {
    palette: { ...palette, H: '#8c5633', T: '#65b9e2', D: '#456f91' },
    rows: [
      '....TTTT....',
      '..TTTTTTTT..',
      '..TTTYTTTTT.',
      '..HFFFFFFH..',
      '..FKFFFFKF..',
      '...FFFFFF...',
      '....FFFF....',
      '...TTTTTT...',
      '..TTTDTTTT..',
      '..FTTTDTTF..',
      '..FFTTWDFF..',
      '...TTTWWT...',
      '...DD..DD...',
      '...KK..KK...',
    ],
  },
  village_camp: {
    palette: { K: '#242827', R: '#a99c7c', r: '#756b58', W: '#e5d6ae', D: '#353b35', G: '#83a06f' },
    rows: [
      '................',
      '................',
      '................',
      '.......K........',
      '......KRK.......',
      '.....KRRRK......',
      '....KRRRRRK.....',
      '...KRRWWRRRK....',
      '..KRRWWWWRRRK...',
      '.KRRWWDDWWRRRK..',
      '.KRRWDDDDWRRRK..',
      '.KRRWDDDDWRRRK..',
      '.KrrDDDDDDrrrK..',
      '.KKKKKKKKKKKKK..',
      '...G........G...',
      '................',
    ],
  },
  village_house: {
    palette: {
      K: '#242827',
      R: '#a89acb',
      r: '#726788',
      W: '#ddc8a0',
      D: '#514e45',
      Y: '#f0ce7b',
      G: '#83a06f',
    },
    rows: [
      '................',
      '...........KK...',
      '...........WK...',
      '.......KK..WK...',
      '......KRRKKWK...',
      '.....KRRRRRRK...',
      '....KRRRRRRRRK..',
      '...KrrrrrrrrrrK.',
      '....KWWWWWWWWK..',
      '....KWYYWWDDWK..',
      '....KWYYWWDDWK..',
      '....KWWWWWDDWK..',
      '....KWWWWWDDWK..',
      '....KKKKKKKKKK..',
      '..G..........G..',
      '................',
    ],
  },
  village_shop: {
    palette: {
      K: '#242827',
      R: '#a89acb',
      r: '#726788',
      W: '#ddc8a0',
      D: '#514e45',
      Y: '#f0ce7b',
      G: '#83a06f',
    },
    rows: [
      '...........KK...',
      '...........WK...',
      '...KKKKKKKKWK...',
      '..KRRRRRRRRRRK..',
      '.KRRRRRRRRRRRRK.',
      '.KrrrrrrrrrrrrK.',
      '..KWWWWWWWWWWK..',
      '..KWYYWYYWYYWK..',
      '..KWYYWYYWYYWK..',
      '.KRRWWRRWWRRWWK.',
      '.KrrWWrrWWrrWWK.',
      '..KWWWWWDDWWWK..',
      '..KWYYWWDDWYWK..',
      '..KWWWWWDDWWWK..',
      '..KKKKKKKKKKKK..',
      '................',
    ],
  },
  village_flowers: {
    palette: { G: '#6fbd78', P: '#ef91b2', Y: '#f1c94f' },
    rows: ['.P...Y...P.', 'PGP.YGY.PGP', '.G...G...G.', 'GGG.GGG.GGG'],
  },
}
